### ISSUE TITLE
Error while running the code - nvdiffrast

### ISSUE THREAD

**Issue by Sanyam-Mehta** [agnJason/PianoMotion10M#1]
I see the following stacktrace when I try to run python draw.py --help. Can you help me identify and resolve the issue?

Traceback (most recent call last):
  File "/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sanyam/GithubRepos/PianoMotion10M/draw.py", line 7, in <module>
    from datasets.show import render_result
  File "/home/sanyam/GithubRepos/PianoMotion10M/datasets/show.py", line 13, in <module>
    glctx = dr.RasterizeGLContext()
  File "/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 221, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/nvdiffrast/torch/ops.py", line 118, in _get_plugin
    torch.utils.cpp_extension.load(name=plugin_name, sources=source_paths, extra_cflags=opts, extra_cuda_cflags=opts+['-lineinfo'], extra_ldflags=ldflags, with_cuda=True, verbose=False)
  File "/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1309, in load
    return _jit_compile(
  File "/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1719, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2123, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'nvdiffrast_plugin_gl': [1/5] /home/sanyam/miniconda3/envs/pianomotion/bin/x86_64-conda-linux-gnu-c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/include -isystem /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/include/TH -isystem /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/include/THC -isystem /home/sanyam/miniconda3/envs/pianomotion/include -isystem /home/sanyam/miniconda3/envs/pianomotion/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
FAILED: glutil.o 
/home/sanyam/miniconda3/envs/pianomotion/bin/x86_64-conda-linux-gnu-c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/include -isystem /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/include/TH -isystem /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/torch/include/THC -isystem /home/sanyam/miniconda3/envs/pianomotion/include -isystem /home/sanyam/miniconda3/envs/pianomotion/include/python3.10 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++17 -DNVDR_TORCH -c /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
In file included from /home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/nvdiffrast/common/glutil.cpp:14:
/home/sanyam/miniconda3/envs/pianomotion/lib/python3.10/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by agnJason** [comment]
It seems that the `EGL/egl.h` is missing. `EGL/egl.h` is in `libegl1-mesa-dev`, so `apt-get install libegl1-mesa-dev` should help.
