### ISSUE TITLE
Error of Visual C++ while running draw.py

### ISSUE THREAD

**Issue by LunaticGhoulPiano** [agnJason/PianoMotion10M#3]
Hello, I'm facing problems while running draw.py.
The error messages are:
```
Traceback (most recent call last):
  File "C:\Users\PoHsu\OneDrive\文件\Github\PianoMotion10M\draw.py", line 7, in <module>
    from datasets.show import render_result
  File "C:\Users\PoHsu\OneDrive\文件\Github\PianoMotion10M\datasets\show.py", line 13, in <module>
    glctx = dr.RasterizeGLContext()
  File "C:\Users\PoHsu\anaconda3\envs\pianomotion\lib\site-packages\nvdiffrast\torch\ops.py", line 228, in __init__
    self.cpp_wrapper = _get_plugin(gl=True).RasterizeGLStateWrapper(output_db, mode == 'automatic', cuda_device_idx)
  File "C:\Users\PoHsu\anaconda3\envs\pianomotion\lib\site-packages\nvdiffrast\torch\ops.py", line 47, in _get_plugin
    raise RuntimeError("Could not locate a supported Microsoft Visual C++ installation")
RuntimeError: Could not locate a supported Microsoft Visual C++ installation
```
My installed Microsoft Visual C++ version is ```Microsoft Visual C++ 2017 Redistributable (x64) - 14.16.27052```, can you help me identify and resolve the issue? thanks.

**Comment by LunaticGhoulPiano** [comment]
I see, it indeed is the VS version error. Thanks!
